name = "csv-do"
route = { pattern = "*/*", zone_name = "csv.do" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-08-23"
logpush = true

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]
